import QuizReportContextProvider from "./context/quizReportContextProvider";
import { Poppins } from 'next/font/google';
import "./globals.css";
import type { Metadata } from "next";


const poppins = Poppins({
  weight: "300",
  style: "normal",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QuizReportContextProvider>
    <html lang="en">
      <body
        className={poppins.className}
      >
        {children}
      </body>
    </html>
    </QuizReportContextProvider>
  );
}
